# 数组跳出循环

## forEach

> forEach 使用 return 可以跳出当前循环；抛出 throw Error()，通过 try catch 去捕获错误可以终止循环终止循环 https://blog.csdn.net/yiyueqinghui/article/details/105832438

```
var arr = [1, 3, 5, 7, 9];
var id = 5;
try {
arr.forEach(function (curItem, i) {
if (curItem === 1) return; //跳过当次循环
console.log(curItem); //输出 3,5
if (curItem === id) {
throw Error(); //满足条件，跳出循环
}
});
} catch (e) {}

```

## map

> 使用 return 可以跳出当前循环；抛出 throw Error()，通过 try catch 去捕获错误可以终止循环终止循环

```

let list=[1,2,3,4,5,6];
try{
  list.map(item=>{
     if(item===3){
         throw Error();
         }
     console.log(item) //1,2
  })
} catch {}


```

## for

```
var arr = [1,3,5,7,9];
var id = 5;
for (var i = 0; i < arr.length; i++) {
     if(arr[i]=== 1) continue;    //跳过当次循环
     console.log(arr[i])
     if (arr[i] === id) {
         break;                   //满足条件，跳出循环
     }
 }

```

## 遍历总结

![遍历](./images/%E9%81%8D%E5%8E%86.png)
